#!/bin/bash

if ! command -v acpi &> /dev/null; then
  exit
fi

battery_info=$(acpi)
if grep -q Charging <<< "$battery_info"; then
  icon=󰂄
else
  icon=󰁹
fi

percentage=$(awk -F', ' '{print $2}' <<< "$battery_info")

printf "$icon %s" "$percentage"
